apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      containers:
      - name: notes-api
        image: notesacr.azurecr.io/notes-api:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: notes-config
        - secretRef:
            name: notes-secrets
