name: Sync FluxCD & Apply K8s Manifests

on:
  push:
    paths:
      - "manifests/**"

jobs:
  flux-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout notes-infra Repo
        uses: actions/checkout@v3

      - name: Sync FluxCD with Latest Manifests
        run: flux reconcile kustomization notes-infra


# name: Deploy Notes API

# on:
#   push:
#     branches:
#       - main

# env:
#   ACR_NAME: notes
#   ACR_URL: notes.azurecr.io
#   APP_NAME: notes-api
#   RESOURCE_GROUP: notes-group
#   AKS_CLUSTER: notes-aks

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v3

#       - name: Login to Azure
#         run: |
#           az login --service-principal \
#           -u ${{ secrets.AZURE_CLIENT_ID }} \
#           -p ${{ secrets.AZURE_CLIENT_SECRET }} \
#           --tenant ${{ secrets.AZURE_TENANT_ID }}

#       - name: Build Docker Image
#         run: |
#           docker build -t $ACR_URL/$APP_NAME:latest .
#           docker tag $ACR_URL/$APP_NAME:latest $ACR_URL/$APP_NAME:${{ github.sha }}

#       - name: Push Docker Image to ACR
#         run: |
#           az acr login --name $ACR_NAME
#           docker push $ACR_URL/$APP_NAME:latest
#           docker push $ACR_URL/$APP_NAME:${{ github.sha }}

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push
#     steps:
#       - name: Get AKS Credentials
#         run: az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_CLUSTER

#       - name: Set Image in Kubernetes Deployment
#         run: |
#           kubectl set image deployment/$APP_NAME \
#           $APP_NAME=$ACR_URL/$APP_NAME:${{ github.sha }}
